### ISSUE TITLE
got Error inflating class <unknown> after launch

### ISSUE THREAD

**Issue by afan2009** [klnusbaum/rxandroidexamples#3]
hi, I cloned and compile the code with Android Studio. And it's upload to the phone that the system is Android 4.4. It got crashed after launch.The crash infomation is as following:

> 07-08 12:33:14.215 18530-18530/? E/AndroidRuntime: FATAL EXCEPTION: main
>                                                    Process: kurtis.rx.androidexamples, PID: 18530
>                                                    android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
>                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:623)
>                                                        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
>                                                        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:672)
>                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
>                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:472)
>                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
>                                                        at kurtis.rx.androidexamples.ExampleAdapter.onCreateViewHolder(ExampleAdapter.java:30)
>                                                        at kurtis.rx.androidexamples.ExampleAdapter.onCreateViewHolder(ExampleAdapter.java:16)
>                                                        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5228)
>                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4453)
>                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
>                                                        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
>                                                        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
>                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
>                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
>                                                        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
>                                                        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
>                                                        at android.view.View.layout(View.java:15138)
>                                                        at android.view.ViewGroup.layout(ViewGroup.java:4862)
>                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
>                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
>                                                        at android.view.View.layout(View.java:15138)
>                                                        at android.view.ViewGroup.layout(ViewGroup.java:4862)
>                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
>                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
>                                                        at android.view.View.layout(View.java:15138)
>                                                        at android.view.ViewGroup.layout(ViewGroup.java:4862)
>                                                        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
>                                                        at android.view.View.layout(View.java:15138)
>                                                        at android.view.ViewGroup.layout(ViewGroup.java:4862)
>                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
>                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
>                                                        at android.view.View.layout(View.java:15138)
>                                                        at android.view.ViewGroup.layout(ViewGroup.java:4862)
>                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
>                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
>                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
>                                                        at android.view.View.layout(View.java:15138)
>                                                        at android.view.ViewGroup.layout(ViewGroup.java:4862)
>                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
>                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
>                                                        at android.view.View.layout(View.java:15138)
>                                                        at android.view.ViewGroup.layout(ViewGroup.java:4862)
>                                                        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2358)
>                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2064)
>                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1232)
>                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6269)
>                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
>                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:591)
>                                                        at android.view.Choreographer.doFrame(Choreographer.java:560)
>                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
>                                                        at android.os.Handler.handleCallback(Handler.java:808)
>                                                        at android.os.Handler.dispatchMessage(Handler.java:103)
>                                                        at android.os.Looper.loop(Looper.java:193)
>                                                        at android.app.ActivityThread.main(ActivityThread.java:5329)
>                                                        at java.lang.reflect.Method.invokeNative(Native Method)
>                                                        at java.lang.reflect.Method.invoke(Method.java:515)
>                                                     at com.android.internal.os.ZygoteInit$Met

**Comment by danzhu10** [comment]
same here...
